version: '3.8'
# add shared configuration
x-shared-config: &shared-config
  image: ${IMAGE_NAME}
  tty: true
  expose:
    - ${PORT_NB}
  ports:
    - ${PORT_NB}:${PORT_NB}
  build:
    context: docker
    dockerfile: dockerfile
    args:
      TF_TAG: 2.14.0-gpu-jupyter
      WORKSPACE_DIR:
  environment:
    PORT_NB:
    WORKSPACE_DIR:
  working_dir: ${WORKSPACE_DIR}
  volumes:
    - ./:${WORKSPACE_DIR}
    - ../tensorflow_datasets:/tensorflow_datasets
    - ../lib:${WORKSPACE_DIR}/lib

services:
  # service using no GPU
  eda-training-cpu:
    profiles:
      - "cpu"
    container_name: tensorflow-cpu
    hostname: tensorflow-cpu
    <<: *shared-config

  # service using GPU
  eda-training-gpu:
    profiles:
      - "gpu"
    container_name: tensorflow-gpu
    hostname: tensorflow-gpu
    <<: *shared-config
    # this section is required for GPU support
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['${GPU_ID}']
            capabilities: [gpu]